[package]
name = "oruuid"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "oruuid"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.21.1"
